# Generated by Django 4.2.2 on 2023-06-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='brief_text',
            field=models.CharField(default='brief description', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
